
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 05 17:54:32 CET 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ALF_OUT = 11;
  public static final int LLCORCH_CL = 7;
  public static final int LLCORCH_OP = 6;
  public static final int CODIGO = 3;
  public static final int ALF_IN = 10;
  public static final int ALM_CL = 19;
  public static final int ALM_OP = 18;
  public static final int ID = 5;
  public static final int MOORE = 4;
  public static final int COMA = 14;
  public static final int EOF = 0;
  public static final int CMP = 2;
  public static final int error = 1;
  public static final int TRANS = 12;
  public static final int LLPARENT_CL = 17;
  public static final int LLPARENT_OP = 16;
  public static final int PUNTO_COMA = 15;
  public static final int ESTADO_INI = 9;
  public static final int COMPORTAMIENTO = 13;
  public static final int ESTADOS = 8;
}

