
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 30 10:14:13 CET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int d = 3;
  public static final int EOF = 0;
  public static final int c = 2;
}

