
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package plmoore;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ALF_OUT = 11;
  public static final int LLCORCH_CL = 7;
  public static final int LLCORCH_OP = 6;
  public static final int CODIGO = 3;
  public static final int ALF_IN = 10;
  public static final int ALM_CL = 19;
  public static final int ALM_OP = 18;
  public static final int ID = 5;
  public static final int MOORE = 4;
  public static final int COMA = 14;
  public static final int EOF = 0;
  public static final int CMP = 2;
  public static final int error = 1;
  public static final int TRANS = 12;
  public static final int LLPARENT_CL = 17;
  public static final int LLPARENT_OP = 16;
  public static final int PUNTO_COMA = 15;
  public static final int ESTADO_INI = 9;
  public static final int COMPORTAMIENTO = 13;
  public static final int ESTADOS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CMP",
  "CODIGO",
  "MOORE",
  "ID",
  "LLCORCH_OP",
  "LLCORCH_CL",
  "ESTADOS",
  "ESTADO_INI",
  "ALF_IN",
  "ALF_OUT",
  "TRANS",
  "COMPORTAMIENTO",
  "COMA",
  "PUNTO_COMA",
  "LLPARENT_OP",
  "LLPARENT_CL",
  "ALM_OP",
  "ALM_CL"
  };
}

