
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 13 17:51:25 CEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 4;
  public static final int POR = 6;
  public static final int EOF = 0;
  public static final int MAS = 3;
  public static final int NUMERO = 9;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int PAREN_I = 7;
  public static final int PUNTOYCOMA = 2;
  public static final int PAREN_D = 8;
}

